#!/bin/bash
# fetch-frontend-env.sh
# Fetches all required frontend environment variables from AWS and writes them to a .env file

set -e

AWS_PROFILE="${AWS_PROFILE:-uicamplify}"
REGION="us-east-2"
USER_POOL_ID="us-east-2_0y75uZuLj"
STAGE="dev"
OUTPUT_FILE="$(dirname "$0")/../frontend.env"

echo "Fetching frontend environment variables..."
echo "Using AWS profile: $AWS_PROFILE"
echo ""

# --- CHAT_ENDPOINT ---
echo "Fetching CHAT_ENDPOINT..."
CHAT_ENDPOINT=$(AWS_PROFILE=$AWS_PROFILE aws cloudformation list-stack-resources \
  --stack-name "amplify-sdd-amplify-js-${STAGE}" \
  --region "$REGION" \
  --query "StackResourceSummaries[?ResourceType=='AWS::Lambda::Url'].PhysicalResourceId" \
  --output text 2>/dev/null || echo "")

if [ -z "$CHAT_ENDPOINT" ]; then
  # Try getting it from CloudFormation outputs
  CHAT_ENDPOINT=$(AWS_PROFILE=$AWS_PROFILE aws cloudformation describe-stacks \
    --stack-name "amplify-sdd-amplify-js-${STAGE}" \
    --region "$REGION" \
    --query "Stacks[0].Outputs[?contains(OutputKey,'Chat') || contains(OutputKey,'chat')].OutputValue | [0]" \
    --output text 2>/dev/null || echo "COULD_NOT_FETCH")
fi
echo "  CHAT_ENDPOINT=$CHAT_ENDPOINT"

# --- COGNITO_CLIENT_ID ---
echo "Fetching COGNITO_CLIENT_ID..."
COGNITO_CLIENT_ID=$(AWS_PROFILE=$AWS_PROFILE aws cognito-idp list-user-pool-clients \
  --user-pool-id "$USER_POOL_ID" \
  --region "$REGION" \
  --query 'UserPoolClients[0].ClientId' \
  --output text 2>/dev/null || echo "COULD_NOT_FETCH")
echo "  COGNITO_CLIENT_ID=$COGNITO_CLIENT_ID"

# --- COGNITO_ISSUER ---
COGNITO_ISSUER="https://cognito-idp.${REGION}.amazonaws.com/${USER_POOL_ID}"
echo "  COGNITO_ISSUER=$COGNITO_ISSUER"

# --- COGNITO_DOMAIN ---
echo "Fetching COGNITO_DOMAIN..."
COGNITO_DOMAIN_PREFIX=$(AWS_PROFILE=$AWS_PROFILE aws cognito-idp describe-user-pool \
  --user-pool-id "$USER_POOL_ID" \
  --region "$REGION" \
  --query 'UserPool.Domain' \
  --output text 2>/dev/null || echo "COULD_NOT_FETCH")

# Build full domain if it's just a prefix (not a custom domain)
if [[ "$COGNITO_DOMAIN_PREFIX" != *"."* ]]; then
  COGNITO_DOMAIN="https://${COGNITO_DOMAIN_PREFIX}.auth.${REGION}.amazoncognito.com"
else
  COGNITO_DOMAIN="https://${COGNITO_DOMAIN_PREFIX}"
fi
echo "  COGNITO_DOMAIN=$COGNITO_DOMAIN"

# --- NEXTAUTH_SECRET ---
NEXTAUTH_SECRET=$(openssl rand -base64 32)
echo "  NEXTAUTH_SECRET=<generated>"

# --- NEXTAUTH_URL (prompt user) ---
echo ""
read -p "Enter your NEXTAUTH_URL (e.g. https://amplify-dev.uic.edu): " NEXTAUTH_URL
echo "  NEXTAUTH_URL=$NEXTAUTH_URL"

# --- API_BASE_URL ---
API_BASE_URL="https://rsssnh53m1.execute-api.${REGION}.amazonaws.com/${STAGE}"
echo "  API_BASE_URL=$API_BASE_URL"

# --- Write to file ---
echo ""
echo "Writing to $OUTPUT_FILE ..."

cat > "$OUTPUT_FILE" <<EOF
# Auto-generated by fetch-frontend-env.sh on $(date)
# Stage: $STAGE | Region: $REGION

CHAT_ENDPOINT=$CHAT_ENDPOINT
COGNITO_CLIENT_ID=$COGNITO_CLIENT_ID
COGNITO_ISSUER=$COGNITO_ISSUER
COGNITO_DOMAIN=$COGNITO_DOMAIN
NEXTAUTH_SECRET=$NEXTAUTH_SECRET
NEXTAUTH_URL=$NEXTAUTH_URL
API_BASE_URL=$API_BASE_URL
EOF

echo ""
echo "Done! Written to: $OUTPUT_FILE"
echo ""
cat "$OUTPUT_FILE"
